# Fehler

Ein [Sumor Cloud](https://sumor.cloud) Tool.  
[Weitere Dokumentation](https://sumor.cloud)
Eine Fehlerbehandlungs-Bibliothek, die Mehrsprachigkeit, vordefinierte Fehlercodes und die Weitergabe von Daten unterstützt.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Installation

```bash
npm i @sumor/error --save
```

## Voraussetzungen

### Node.JS-Version

Erfordert Node.JS-Version 16.x oder höher

### Erfordern Node.JS ES-Modul

Da dieses Paket in ES-Modul geschrieben ist,
bitte ändern Sie den folgenden Code in Ihrer `package.json`-Datei:

```json
{
  "type": "module"
}
```

## Verwendung

### Fehler definieren

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Benutzer nicht gefunden',
    USER_EXISTED: 'Benutzer {name} existiert'
  }
})

throw new MyError('USER_NOT_FOUND')
// Ausgabe: Error: Benutzer nicht gefunden

throw new MyError('USER_EXISTED', { name: 'Alice' })
// Ausgabe: Error: Benutzer Alice existiert
```

### Mehrsprachigkeit

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  language: 'en', // Standardsprache
  code: {
    USER_NOT_FOUND: 'Benutzer nicht gefunden',
    USER_EXISTED: 'Benutzer {name} existiert'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Benutzer nicht gefunden',
      USER_EXISTED: 'Benutzer {name} existiert'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // Fehlermeldung ändern
console.log(error)
// Ausgabe: Error: Benutzer Alice existiert

error.language = 'zh' // Fehlermeldung ändern
console.log(error)
// Ausgabe: Error: Benutzer Alice existiert
```

### Fehler in JSON konvertieren

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Benutzer nicht gefunden',
    USER_EXISTED: 'Benutzer {name} existiert'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// Ausgabe: {"code":"USER_EXISTED","message":"Benutzer Alice existiert"}
```

### Unterliegender Fehler

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Feldüberprüfung fehlgeschlagen',
    FIELD_CANNOT_EMPTY: 'Feld {name} darf nicht leer sein',
    FIELD_TOO_LONG: 'Feld {name} ist zu lang'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Feldüberprüfung fehlgeschlagen',
      FIELD_CANNOT_EMPTY: 'Feld {name} darf nicht leer sein',
      FIELD_TOO_LONG: 'Feld {name} ist zu lang'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'Benutzername' }),
  new MyError('FIELD_TOO_LONG', { name: 'Passwort' })
])

console.log(error.json())
/* 
Ausgabe: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Feldüberprüfung fehlgeschlagen",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Feld Benutzername darf nicht leer sein"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Feld Passwort ist zu lang"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
Ausgabe:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Feldüberprüfung fehlgeschlagen",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Feld Benutzername darf nicht leer sein"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Feld Passwort ist zu lang"
    }
  ]
}
*/
```

### Standardfehler kombinieren

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Feldüberprüfung fehlgeschlagen',
    FIELD_CANNOT_EMPTY: 'Feld {name} darf nicht leer sein',
    FIELD_TOO_LONG: 'Feld {name} ist zu lang'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'Benutzername' }),
  new MyError('FIELD_TOO_LONG', { name: 'Passwort' }),
  new Error('Unbekannter Fehler')
])

console.log(error.json())
/*
Ausgabe:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Feldüberprüfung fehlgeschlagen",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"Feld Benutzername darf nicht leer sein"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"Feld Passwort ist zu lang"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Unbekannter Fehler"
    }
  ]
}
 */
```
