# error

Una [Sumor Cloud](https://sumor.cloud) Herramienta.  
[Más Documentación](https://sumor.cloud)
Una biblioteca de manejo de errores que admite múltiples idiomas, códigos de error predefinidos y paso de datos.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Test](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Coverage](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Audit](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Instalación

```bash
npm i @sumor/error --save
```

## Prerrequisitos

### Versión de Node.JS

Se requiere Node.JS versión 16.x o superior

### Requerir módulo ES de Node.JS

Dado que este paquete está escrito en módulo ES,
por favor cambia el siguiente código en tu archivo `package.json`:

```json
{
  "type": "module"
}
```

## Uso

### Definir Error

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Usuario no encontrado',
    USER_EXISTED: 'Usuario {name} ya existente'
  }
})

throw new MyError('USER_NOT_FOUND')
// output: Error: Usuario no encontrado

throw new MyError('USER_EXISTED', { name: 'Alice' })
// output: Error: Usuario Alice ya existente
```

### Multi-idioma

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  language: 'en', // idioma por defecto
  code: {
    USER_NOT_FOUND: 'Usuario no encontrado',
    USER_EXISTED: 'Usuario {name} ya existente'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Usuario no encontrado',
      USER_EXISTED: 'Usuario {name} ya existe'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // cambiar idioma del Error
console.log(error)
// output: Error: Usuario Alice ya existente

error.language = 'zh' // cambiar idioma del Error
console.log(error)
// output: Error: Usuario Alice ya existe
```

### Convertir Error a JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Usuario no encontrado',
    USER_EXISTED: 'Usuario {name} ya existente'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// output: {"code":"USER_EXISTED","message":"Usuario Alice ya existente"}
```

### Error Subyacente

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Fallo en la verificación del campo',
    FIELD_CANNOT_EMPTY: 'El campo {name} no puede estar vacío',
    FIELD_TOO_LONG: 'El campo {name} es demasiado largo'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Fallo en la verificación del campo',
      FIELD_CANNOT_EMPTY: 'El campo {name} no puede estar vacío',
      FIELD_TOO_LONG: 'El campo {name} es demasiado largo'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'nombre de usuario' }),
  new MyError('FIELD_TOO_LONG', { name: 'contraseña' })
])

console.log(error.json())
/* 
output: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Fallo en la verificación del campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"El campo nombre de usuario no puede estar vacío"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"El campo contraseña es demasiado largo"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
output:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Fallo en la verificación del campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"El campo nombre de usuario no puede estar vacío"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"El campo contraseña es demasiado largo"
    }
  ]
}
*/
```

### Combinar Error Estándar

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Fallo en la verificación del campo',
    FIELD_CANNOT_EMPTY: 'El campo {name} no puede estar vacío',
    FIELD_TOO_LONG: 'El campo {name} es demasiado largo'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'nombre de usuario' }),
  new MyError('FIELD_TOO_LONG', { name: 'contraseña' }),
  new Error('Error Desconocido')
])

console.log(error.json())
/*
output:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Fallo en la verificación del campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"El campo nombre de usuario no puede estar vacío"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"El campo contraseña es demasiado largo"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Error Desconocido"
    }
  ]
}
 */
```
