# エラー

[Sumor Cloud](https://sumor.cloud)ツール。  
[詳細なドキュメント](https://sumor.cloud/error)
複数言語をサポートしたエラーハンドリングライブラリ、事前定義されたエラーコード及びデータの受け渡しをサポートしています。

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![テスト](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![カバレッジ](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![監査](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## インストール

```bash
npm i @sumor/error --save
```

## 必要条件

### Node.JSのバージョン

Node.JSバージョン16.x以上が必要です

### Node.JS ESモジュールの要件

このパッケージはESモジュールで書かれているので、 `package.json`ファイル内の以下のコードを変更してください:

```json
{
  "type": "module"
}
```

## 使用方法

### エラーの定義

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}が存在します'
  }
})

throw new MyError('USER_NOT_FOUND')
// 出力: Error: ユーザーが見つかりません

throw new MyError('USER_EXISTED', { name: 'Alice' })
// 出力: Error: ユーザーAliceが存在します
```

### 複数言語

```js
import defineError from '@sumor/error'

const MyError = defineError({
  language: 'en', // デフォルト言語
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}が存在します'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'ユーザーが見つかりません',
      USER_EXISTED: 'ユーザー{name}が存在します'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // エラーの言語を変更
console.log(error)
// 出力: Error: ユーザーAliceが存在します

error.language = 'zh' // エラーの言語を変更
console.log(error)
// 出力: Error: ユーザーAliceが存在します
```

### エラーをJSONに変換

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    USER_NOT_FOUND: 'ユーザーが見つかりません',
    USER_EXISTED: 'ユーザー{name}が存在します'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// 出力: {"code":"USER_EXISTED","message":"ユーザーAliceが存在します"}
```

### エラーが発生した理由

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールドの検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできません',
    FIELD_TOO_LONG: 'フィールド{name}が長すぎます'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'フィールドの検証に失敗しました',
      FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできません',
      FIELD_TOO_LONG: 'フィールド{name}が長すぎます'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザー名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' })
])

console.log(error.json())
/* 
出力: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールドの検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザー名は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードが長すぎます"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールドの検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザー名は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードが長すぎます"
    }
  ]
}
*/
```

### 標準エラーを組み合わせる

```js
import defineError from '@sumor/error'

const MyError = defineError({
  code: {
    FIELD_VERIFY_FAILED: 'フィールドの検証に失敗しました',
    FIELD_CANNOT_EMPTY: 'フィールド{name}は空にできません',
    FIELD_TOO_LONG: 'フィールド{name}が長すぎます'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'ユーザー名' }),
  new MyError('FIELD_TOO_LONG', { name: 'パスワード' }),
  new Error('不明なエラー')
])

console.log(error.json())
/*
出力:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"フィールドの検証に失敗しました",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"フィールドユーザー名は空にできません"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"フィールドパスワードが長すぎます"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"不明なエラー"
    }
  ]
}
 */
```
