# Erro

Uma ferramenta [Sumor Cloud](https://sumor.cloud).
[Documentação Adicional](https://sumor.cloud)

Uma biblioteca de manipulação de erros que suporta vários idiomas, códigos de erro predefinidos e passagem de dados.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Teste](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Cobertura](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Auditoria](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Instalação

```bash
npm i @sumor/error --save
```

## Pré-requisitos

### Versão do Node.JS

Requer a versão do Node.JS 16.x ou superior

### Requer módulo ES do Node.JS

Como este pacote é escrito em módulo ES,
por favor altere o seguinte código em seu arquivo `package.json`:

```json
{
  "type": "module"
}
```

## Uso

### Definir Erro

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Usuário não encontrado',
    USER_EXISTED: 'Usuário {name} existente'
  }
})

throw new MyError('USER_NOT_FOUND')
// saída: Error: Usuário não encontrado

throw new MyError('USER_EXISTED', { name: 'Alice' })
// saída: Error: Usuário Alice existente
```

### Multilinguagem

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  language: 'en', // idioma padrão
  code: {
    USER_NOT_FOUND: 'Usuário não encontrado',
    USER_EXISTED: 'Usuário {name} existente'
  },
  i18n: {
    zh: {
      USER_NOT_FOUND: 'Usuário não encontrado',
      USER_EXISTED: 'Usuário {name} existente'
    }
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
error.language = 'en' // mudar idioma do erro
console.log(error)
// saída: Error: Usuário Alice existente

error.language = 'zh' // mudar idioma do erro
console.log(error)
// saída: Error: Usuário Alice existente
```

### Converter Erro para JSON

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    USER_NOT_FOUND: 'Usuário não encontrado',
    USER_EXISTED: 'Usuário {name} existente'
  }
})

const error = new MyError('USER_EXISTED', { name: 'Alice' })
console.log(error.json())
// saída: {"code":"USER_EXISTED","message":"Usuário Alice existente"}
```

### Erro Subjacente

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Falha na verificação do campo',
    FIELD_CANNOT_EMPTY: 'O campo {name} não pode estar vazio',
    FIELD_TOO_LONG: 'O campo {name} é muito longo'
  },
  i18n: {
    zh: {
      FIELD_VERIFY_FAILED: 'Falha na verificação do campo',
      FIELD_CANNOT_EMPTY: 'O campo {name} não pode estar vazio',
      FIELD_TOO_LONG: 'O campo {name} é muito longo'
    }
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'username' }),
  new MyError('FIELD_TOO_LONG', { name: 'password' })
])

console.log(error.json())
/* 
saída: 
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Falha na verificação do campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"O campo username não pode estar vazio"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"O campo password é muito longo"
    }
  ]
}
*/

error.language = 'zh'
console.log(error.json())
/*
saída:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Falha na verificação do campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"O campo username não pode estar vazio"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"O campo password é muito longo"
    }
  ]
}
*/
```

### Combinar Erro Padrão

```js
import defineError from '@sumor/error'

const MyError = defineError({
  name: 'MyError',
  code: {
    FIELD_VERIFY_FAILED: 'Falha na verificação do campo',
    FIELD_CANNOT_EMPTY: 'O campo {name} não pode estar vazio',
    FIELD_TOO_LONG: 'O campo {name} é muito longo'
  }
})

const error = new MyError('FIELD_VERIFY_FAILED', {}, [
  new MyError('FIELD_CANNOT_EMPTY', { name: 'username' }),
  new MyError('FIELD_TOO_LONG', { name: 'password' }),
  new Error('Erro Desconhecido')
])

console.log(error.json())
/*
saída:
{
  "code":"FIELD_VERIFY_FAILED",
  "message":"Falha na verificação do campo",
  "errors":[
    {
      "code":"FIELD_CANNOT_EMPTY",
      "message":"O campo username não pode estar vazio"
    },{
      "code":"FIELD_TOO_LONG",
      "message":"O campo password é muito longo"
    },{
      "code":"UNKNOWN_ERROR",
      "message":"Erro Desconhecido"
    }
  ]
}
 */
```
