# erro

Uma [Ferramenta Sumor Cloud](https://sumor.cloud).  
[Documentação Adicional](https://sumor.cloud/error)
Um biblioteca de tratamento de erro com suporte a vários idiomas, códigos de erro predefinidos e passagem de dados.

[![CI](https://github.com/sumor-cloud/error/actions/workflows/ci.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ci.yml)
[![Teste](https://github.com/sumor-cloud/error/actions/workflows/ut.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/ut.yml)
[![Cobertura](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/coverage.yml)
[![Auditoria](https://github.com/sumor-cloud/error/actions/workflows/audit.yml/badge.svg)](https://github.com/sumor-cloud/error/actions/workflows/audit.yml)

## Instalação

```bash
npm i @sumor/error --save
```

## Pré-requisitos

### Versão do Node.JS

Requer Node.JS na versão 16.x ou superior

### Exigir módulo ES do Node.JS

Como este pacote é escrito como um módulo ES, por favor altere o trecho a seguir no seu arquivo `package.json`:

```json
{
  "type": "module"
}
```

## Uso

### Definir Erro

```js
import defineError from '@sumor/error'

const MeuErro = defineError({
  code: {
    USUÁRIO_NÃO_ENCONTRADO: 'Usuário não encontrado',
    USUÁRIO_EXISTENTE: 'Usuário {nome} já existe'
  }
})

throw new MeuErro('USUÁRIO_NÃO_ENCONTRADO')
// saída: Error: Usuário não encontrado

throw new MeuErro('USUÁRIO_EXISTENTE', { nome: 'Alice' })
// saída: Error: Usuário Alice já existe
```

### Multi-idioma

```js
import defineError from '@sumor/error'

const MeuErro = defineError({
  language: 'en', // idioma padrão
  code: {
    USUÁRIO_NÃO_ENCONTRADO: 'Usuário não encontrado',
    USUÁRIO_EXISTENTE: 'Usuário {nome} já existe'
  },
  i18n: {
    zh: {
      USUÁRIO_NÃO_ENCONTRADO: 'Usuário não encontrado',
      USUÁRIO_EXISTENTE: 'Usuário {nome} já existe'
    }
  }
})

const erro = new MeuErro('USUÁRIO_EXISTENTE', { nome: 'Alice' })
erro.language = 'en' // alterar idioma do erro
console.log(erro)
// saída: Error: Usuário Alice já existe

erro.language = 'zh' // alterar idioma do erro
console.log(erro)
// saída: Error: Usuário Alice já existe
```

### Converter Erro para JSON

```js
import defineError from '@sumor/error'

const MeuErro = defineError({
  code: {
    USUÁRIO_NÃO_ENCONTRADO: 'Usuário não encontrado',
    USUÁRIO_EXISTENTE: 'Usuário {nome} já existe'
  }
})

const erro = new MeuErro('USUÁRIO_EXISTENTE', { nome: 'Alice' })
console.log(erro.json())
// saída: {"code":"USUÁRIO_EXISTENTE","message":"Usuário Alice já existe"}
```

### Erro Subjacente

```js
import defineError from '@sumor/error'

const MeuErro = defineError({
  code: {
    VERIFICAÇÃO_CAMPO_FALHOU: 'Verificação do campo falhou',
    CAMPO_NÃO_PODE_VAZIO: 'Campo {nome} não pode estar vazio',
    CAMPO_MUITO_LONGO: 'Campo {nome} está muito longo'
  },
  i18n: {
    zh: {
      VERIFICAÇÃO_CAMPO_FALHOU: 'Verificação do campo falhou',
      CAMPO_NÃO_PODE_VAZIO: 'Campo {nome} não pode estar vazio',
      CAMPO_MUITO_LONGO: 'Campo {nome} está muito longo'
    }
  }
})

const erro = new MeuErro('VERIFICAÇÃO_CAMPO_FALHOU', {}, [
  new MeuErro('CAMPO_NÃO_PODE_VAZIO', { nome: 'nome de usuário' }),
  new MeuErro('CAMPO_MUITO_LONGO', { nome: 'senha' })
])

console.log(erro.json())
/* 
saída: 
{
  "code":"VERIFICAÇÃO_CAMPO_FALHOU",
  "message":"Verificação do campo falhou",
  "errors":[
    {
      "code":"CAMPO_NÃO_PODE_VAZIO",
      "message":"Campo nome de usuário não pode estar vazio"
    },{
      "code":"CAMPO_MUITO_LONGO",
      "message":"Campo senha está muito longo"
    }
  ]
}
*/

erro.language = 'zh'
console.log(erro.json())
/*
saída:
{
  "code":"VERIFICAÇÃO_CAMPO_FALHOU",
  "message":"Campo nome de usuário não pode estar vazio",
  "errors":[
    {
      "code":"CAMPO_NÃO_PODE_VAZIO",
      "message":"Campo nome de usuário não pode estar vazio"
    },{
      "code":"CAMPO_MUITO_LONGO",
      "message":"Campo senha está muito longo"
    }
  ]
}
*/
```

### Combinar Erro Padrão

```js
import defineError from '@sumor/error'

const MeuErro = defineError({
  code: {
    VERIFICAÇÃO_CAMPO_FALHOU: 'Verificação do campo falhou',
    CAMPO_NÃO_PODE_VAZIO: 'Campo {nome} não pode estar vazio',
    CAMPO_MUITO_LONGO: 'Campo {nome} está muito longo'
  }
})

const erro = new MeuErro('VERIFICAÇÃO_CAMPO_FALHOU', {}, [
  new MeuErro('CAMPO_NÃO_PODE_VAZIO', { nome: 'nome de usuário' }),
  new MeuErro('CAMPO_MUITO_LONGO', { nome: 'senha' }),
  new Error('Erro Desconhecido')
])

console.log(erro.json())
/*
saída:
{
  "code":"VERIFICAÇÃO_CAMPO_FALHOU",
  "message":"Verificação do campo falhou",
  "errors":[
    {
      "code":"CAMPO_NÃO_PODE_VAZIO",
      "message":"Campo nome de usuário não pode estar vazio"
    },{
      "code":"CAMPO_MUITO_LONGO",
      "message":"Campo senha está muito longo"
    },{
      "code":"ERRO_DESCONHECIDO",
      "message":"Erro Desconhecido"
    }
  ]
}
 */
```
